apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    app.kubernetes.io/managed-by: Helm
spec:
  path: {{ .Values.route.path }}
  to:
    kind: Service
    name: {{ .Values.service.name }}
  tls: null
  port:
    targetPort: {{ .Values.image.port }}